TAG_MAP = {
    "python": "ProgrammingLanguages",
    "java":"ProgrammingLanguages",
    "c":"ProgrammingLanguages",
    "react":"FrontendDevelopment",
    "angular":"FrontendDevelopment",
    "spring boot":"BackendFrameworks",
    "django":"BackendFrameworks",
    "git":"VersionControl",
    "github":"VersionControl",
    "aws":"CloudExperience",
    "gcp":"CloudExerience",
    "docker":"DevOps",
    "kubernetes":"DevOps",
    "jenkins":"AutomationPipeline",
    "ci/cd":"AutomationPipeline",
    "sql":"DatabaseKnowledge",
    "postgressql":"DatabaseKnowledge",
    "mongodb":"DatabaseKnowledge",
    "jira":"ProjectManagement",
    "agile":"ProjectManagement",
    "scrum":"ProjectMangaement",
    "security+":"Cybersecurity",
    "penetration testing":"CyberSecurity",
    "machine learning":"MLExperience",
    "sklearn":"MLExperience",
    "nlp":"AI/LanguageModels",
    "transformers":"AI/LanguageModels",
    "rest api": "APIDesign",
    "graphql":"APIDesign",
    "mentoring":"CommunicationSkills",
    "teaching":"CommunicationSkills"
}